<button onclick="showModal()" class="button is-normal is-primary modal-button" data-target="modal" id="show-modal" aria-haspopup="true">Laisser un commentaire</button>
<div id="modal" class="modal">
  <div class="modal-background"></div>
  <div class="modal-card">
    <header class="modal-card-head">
      <p class="modal-card-title">Ajouter un commentaire</p>
      <button onclick="hideModal()" class="delete" id="hide-modal"  aria-label="Fermer"></button>
    </header>
    <form method="post" action="post.php?id_post=<?= $_GET['id_post'] ?>" class="modal-card-body">

      <!-- récupération de la valeur "username" dans $_SESSION -->
      <input type="hidden" name="id_user" value="<?= $_SESSION['username'] ?>">

      <!-- récupération de la valeur "id_post" dans $_GET -->
      <input type="hidden" name="id_post" value="<?= $_GET['id_post'] ?>">
      
      <!-- commentaire -->
      <div class="content">
        <textarea name="content" class="textarea" placeholder="Entrer votre commentaire"></textarea>
      </div>
        <button class="button is-success">Enregistrer le commentaire</button>
    </form>
  </div>
</div>