<section class="section container ">
    <?php foreach ($posts as $post) : ?>
    <div class="card">
        <div class="card-content">
            <div class="media">
                <div class="media-content">
                    <p class="title"><?= $post['title'] ?></p>
                </div>
            </div>
            <div class="content">
                <p><?= $post['content'] ?><a href="./post.php?id_post=<?= $post['id_post'] ?>">... lire la suite</a></p>
            </div>
            <div class="content">
                <h5>Auteur : <?= $post['username'] ?></h5>
                <p>Catégorie : <?= $post['name_categorie'] ?></p>
                <br />
                <time><?= $post['date'] ?> à <?= $post['heure'] ?></time>
            </div>
        </div>
    </div>
    <?php endforeach ?>
</section>
<section class="container section">
    <div>
        <nav class="pagination is-centered" role="navigation" aria-label="pagination">
            <a class="pagination-previous">Previous</a>
            <a class="pagination-next">Next page</a>
            <ul class="pagination-list">
                <li>
                    <a class="pagination-link" aria-label="Goto page 1">1</a>
                </li>
                <li><span class="pagination-ellipsis">&hellip;</span></li>
                <li>
                    <a class="pagination-link" aria-label="Goto page 45">45</a>
                </li>
                <li>
                    <a class="pagination-link is-current" aria-label="Page 46" aria-current="page">46</a
                    >
                </li>
                <li>
                    <a class="pagination-link" aria-label="Goto page 47">47</a>
                </li>
                <li><span class="pagination-ellipsis">&hellip;</span></li>
                <li>
                    <a class="pagination-link" aria-label="Goto page 86">86</a>
                </li>
            </ul>
        </nav>
    </div>
</section>
