<section class="section container">
    <?php foreach ($posts as $post) : ?>
    <div class="card">
        <div class="card-content">
            <div class="media">
                <div class="media-content">
                    <p class="title"><?= $post['title'] ?></p>
                </div>
            </div>
            <div class="content">
                <p><?= $post['content'] ?><a href="./post.php?id_post=<?= $post['id_post'] ?>">... lire la suite</a>
                </p>
            </div>
            <div class="content">
                <h5>Auteur : <?= $post['username'] ?></h5>
                <p>Catégorie : <?= $post['name_categorie'] ?></p>
                <br />
                <time><?= $post['date'] ?> à <?= $post['heure'] ?></time>
            </div>
        </div>
    </div>
    <?php endforeach ?>
</section>
<section class="container section">
    <div>
        <nav class="pagination is-centered">
            <a <?php if ($currentPage <= 1): ?> disabled<?php endif ?> class="pagination-previous" href="./index.php?page=<?= $currentPage - 1 ?>">Previous</a>
            <a class="pagination-next" <?php if($currentPage >= $totalPages): ?> disabled <?php endif ?> href="./index.php?page=<?= $currentPage + 1 ?>">Next page</a>
            <ul class="pagination-list">
                <?php for ($page = 1; $page <= $totalPages; $page++): ?>
                <li class="">
                    <a <?php if ($page === $currentPage): ?>
                    active
                    <?php endif ?> class="pagination-link" href="./index.php?page=<?= $page?>"><?= $page ?></a>
                </li>
                <?php endfor ?>
            </ul>
        </nav>
    </div>
</section>
