<div class="container">
        <!-- <div class="column is-4"> -->
            <h4 class="title is-4">Connexion</h4>
            <form method="post" action="./login.php">
                <div class="field">
                    <label class="label">Pseudo</label>
                    <div class="control">
                        <input class="input" type="text" value="" name="username">
                    </div>
                </div>
                <div class="field">
                    <label class="label">Mot de passe</label>
                    <div class="control">
                        <input class="input" type="password" value="" name="password">
                    </div>
                </div>

                <div class="field ">
                    <div class="control">
                        <button class="button is-link">Se connecter</button>
                    </div>
                </div>
            </form>
        <!-- </div> -->
    </div>
