<div class="container">
    <form action="add_post.php" method="post">
        <div class="field">
            <label class="label">Titre</label>
            <div class="control">
                <input class="input" type="text" placeholder="Mon super article" name="title">
            </div>
        </div>

        <div class="field">
            <label class="label">Catégorie</label>
            <div class="control">
                <div class="select">
                    <select name="id_categorie">
                        <?php foreach ($categories as $category) : ?>
                            <option value="<?= $category['id_category'] ?>"><?php echo $category['name_categorie'] ?> </option>
                        <?php endforeach ?>
                    </select>
                </div>
            </div>
        </div>

        <div class="field">
            <label class="label">Contenu</label>
            <div class="control">
                <textarea class="textarea" placeholder="" name="content"></textarea>
            </div>
        </div>

        <div class="field">
            <div class="control">
                <button class="button is-link">Poster !</button>
            </div>
        </div>
    </form>
</div>