<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css"/>
        <link rel="stylesheet" href="../css/style.css">
        <title><?=$title?></title>
    </head>
    <body>
        <header>
            <nav class="navbar" role="navigation" aria-label="main navigation">
                <div class="navbar-brand">
                    <a class="navbar-item" ><strong>Administration</strong></a>

                    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
                        <span aria-hidden="true"></span>
                        <span aria-hidden="true"></span>
                        <span aria-hidden="true"></span>
                    </a>
                </div>

                <div id="navbarBasicExample" class="navbar-menu">
                    <div class="navbar-start">
                        <a href="" class="navbar-item"> Ajouter un article </a>
                        <a href="" class="navbar-item"> Liste des articles</a>
                        <a href="./users.php" class="navbar-item"> Liste des utilisateurs</a>
                    </div>

                    <div class="navbar-end">
                        <div class="navbar-item">
                            <?php require 'auth_buttons.phtml' ?>
                        </div>
                    </div>
                </div>
            </nav>
        </header>
        <main class="container">
            <?php require $template . '.phtml' ?>
        </main>
        <footer class="footer">
            <div class="content has-text-centered">
                <p>&copy; Blog</p>
            </div>
        </footer>
    </body>
</html>
