<table class="content-table m-auto">
  <thead>
    <tr>
      <th></th>
      <th>ID</th>
      <th>Rank</th>
      <th>Pseudo</th>
      <th>Email</th>
      <th colspan="2">...</th>
    </tr>
  </thead>
  <tbody>
    <?php foreach ($users as $user) : ?>
        <tr>
            <td><?php if ($user['rank'] > 1) : ?><i class="fas fa-splotch"></i> <?php endif; ?></td>
            <td><?= $user['id_user'] ?></td>
            <td><?= $user['rank'] ?></td>
            <td><?= $user['username'] ?></td>
            <td><?= $user['email'] ?></td>
            <td>Editer</td>
            <td>Supprimer</td>
        </tr>
    <?php endforeach; ?>
  </tbody>
</table>