<table class="content-table">
  <thead>
    <tr>
      <th>ID</th>
      <th>Rank</th>
      <th>Pseudo</th>
      <th>Email</th>
      <th>...</th>
    </tr>
  </thead>
  <tbody>
    <?php foreach ($users as $user) : ?>
        <tr>
            <td><?= $user['id_user'] ?></td>
            <td><?= $user['rank'] ?></td>
            <td><?= $user['username'] ?></td>
            <td><?= $user['email'] ?></td>
            <td>Editer</td>
        </tr>
    <?php endforeach; ?>
  </tbody>
</table>